### PR TITLE
#12 adds entity generation support

### PR DESCRIPTION
**Pull request by willbuck**
With this PR, the work I've started against Isuee #9 (generate a working app & clarify the readme) is now able to also generate the server-side entity files (given them being specified in a `.jhipster/` folder, as they are in the sample apps). I'm not 1000% certain that any and all permutations of entity definitions are covered here (definitely not the other DBs like cassandra or mongo), but the ones provided in the sample app (`BankAccount`, `Operation`, and `Label`) are definitely working; I've done some testing locally.

Feedback is welcome as I continue to learn more about how to put these generators together, thank you for your time!

### CODE REVIEW

**Comment by willbuck** [comment]
@atomfrede @sendilkumarn @jdubois @jameskleeh can't add you as reviewers but your feedback is appreciated!

**Comment by jdubois** [comment]
It's hard to tell as you add 5,000 LOC - it's sad that you can't reuse what we already have, but I guess the changes are too important?

**Comment by willbuck** [comment]
@jdubois part of what I'm trying to figure out is what is and is not important. I am getting a better hang of how best to reuse things (I think this work is doing a pretty good job of that in the client portion, needing no customization for these entities and minimal for the initial buildout), but certainly there is a *lot* to unpack. That's why I wanted to solicit feedback. 

"This feels like a lot" is helpful feedback to an extent, but what might help more is guidance on what to be doing differently. The initial project didn't generate an app that functioned at all like the sample app, and I'm trying to get it to a baseline where it does, so that changes can get smaller from there. That feels like a good approach, but is there a preference for something different?

**Comment by jdubois** [comment]
Unfortunately, for entities I'm not sure there is a better model than what you current do. There's probably going to be changes a little bit everywhere in the source code, so it's really hard to find some common code that we could extract and re-use.
Do you have an example, where I could see the difference between what we current generate, and what you aim to generate? For something simple, like just a table for an SQL database. BTW, I don't recommend you do anything more than SQL, this is what 80% of people are using (the rest being mostly MongoDB).

**Comment by willbuck** [comment]
@jdubois absolutely! I'm actually reusing the Liquibase / SQL generation from the base generator, as our table structures are compatible with yours. 

Mostly the things that change have to do with imports; while Micronaut projects have pretty similar structure in their user classes to Spring Boot, the imports are obviously different, and thus the usage differs in some cases (many of our apis are remarkably similar, though).

Take for example, `EntityRepository.java.ejs`. Here you can see our implementation's going to have all micronaut imports
 
https://github.com/willbuck/generator-jhipster-micronaut/pull/2/files#diff-c714ea8c4adde0198c1f03bcd907ad11R26-R35

whereas the base generator has all spring imports:

https://github.com/jhipster/generator-jhipster/blob/master/generators/entity-server/templates/src/main/java/package/repository/EntityRepository.java.ejs#L26

So mostly what I've changed involves stuff like that.

**Comment by willbuck** [comment]
Closing this PR in favor of one to the repo proper

**Pull request closed without merging**
